name: Latest Github activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from Github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "GITHUB"
          commit_message: "Updated readme with the latest Github data"
          feed_list: "https://github.com/SpctrX"